on: [push]

env:
  VERSION: "1.0.${{ github.run_number }}"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          scope: ${{ github.repository_owner }}
          registry-url: https://npm.pkg.github.com

      - name: Create a package called @${{ github.repository }}
        run: |
          echo '{
            "name": "@${{ github.repository }}",
            "version": "1.0.0",
            "description": "Example publishing an npm package.",
            "repository": "https://github.com/${{ github.repository }}"
          }' > package.json

      - name: Add README.md to package
        run: echo '### README for package version ${{ env.VERSION }}' > README.md

      - name: Set package version to ${{ env.VERSION }}
        run: npm version ${{ env.VERSION }} --no-git-tag-version

      - name: Build the package
        run: npm pack

      - name: Publish the package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
